baseURL = "http://ecwu.xyz/"
languageCode = "en-us"
title = "ECWU.XYZ Landing"
theme = "hugo-theme-shell"

[Params]
  # Note: This is for the meta description, which is different from the "description" displayed in the terminal.
  description = "ECWU.XYZ Landing Page"
  [Params.Terminal]
  # Note: color schema
  # Note: You can choose between
  # Note: ["monokai", "powershell", "gruvbox_light", "gruvbox_dark", "solarized_light", "solarized_dark", "ubuntu", "retro"]
  schema = "solarized_dark"

  # Note: in terminal
  # [userName]@[pcName]:~/$ cd [workDir]
  # [userName]@[pcName]:~/[workDir]$ cat [profile]
  #
  # [description]
  #
  # Note: if you set Params.Tree > use = true
  # [userName]@[pcName]:~/[workDir]$ tree ./[folderName]/
  # ./[folderName]/
  # ...
  # Note: result of the tree command
  userName = "ecwu"
  pcName = "mbp"
  workDir = "me"
  profile = "profile.txt"

  # Note: speed at which text is displayed on the terminal
  # Note: if set to 0, typing animation will be disabled
  # Note:
  # Note: If you want to enable Mathjax, you need to set it to 0
  # Note: and set "math: true" at front matter in your Markdown file
  terminalDelay = 0

  # Note: speed at which text is displayed on the activity pages
  # Note: if set to 0, typing animation will be disabled
  # Note: 
  # Note: If you want to enable Mathjax, you need to set it to 0
  # Note: and set "math: true" at front matter in your Markdown file
  activityDelay = 5

  description = """
  Jack Wu (ECWU)
  This is the landing page for ECWU.xyz
  You can checkout my other works.

  """

  # Note: If you want to use a Markdown file, you can use the following
  # description = "/description.md"
  # Note: and put the description.md in /content/description.md

  [Params.Tree]
  use = true
  folderName = "my_stuff"
  # Note: ["ACTIVITY", "URL or PATH TO YOUR MARKDOWN FILE"]
  files = [ 
    ["main_site(blog)", "https://ecwuuuuu.com/"],
    ["photos", "https://foto.ecwuuuuu.com/"],
    ["vaultwarden", "https://k.ecwu.xyz/"],
    ["TTRSS", "https://rss.ecwu.xyz"]
    ["instagram", "https://www.instagram.com/ecwuuuuu/"],
    ["github", "https://github.com/ecwu/"],
    ["linkedin", "https://www.linkedin.com/in/zhenghaowu/"],
    ["researchgate", "https://www.researchgate.net/profile/Zhenghao-Wu"],
    ["bilibili", "https://space.bilibili.com/509461"]
  ]
